### ISSUE TITLE
This login code doesnt work

### ISSUE THREAD

**Issue by smaheshbhat** [tkanhe/Fyers-API-Access-Token-Generation-V2#1]
content:b'{"s": "error", "code": -1031, "failed_attempts": 2, "message": "recaptcha token is not provided"}'

The above error for the line

r1 = s.post('https://api.fyers.in/vagator/v1/login', data=data1)

**Comment by tkanhe** [comment]
I didn't get the captcha problem yet, so I can't solve it, Don't try to run the script multiple times in a day (as once the token is generated, it's valid for the day); that way, Google might think you are a robot. I've added a user agent in the following file. Let me know if it works for you : https://github.com/tkanhe/Fyers-API-Access-Token-Generation-V2/blob/main/Fyers%20Access%20Token%20with%20added%20User%20Agent.py

**Comment by smaheshbhat** [comment]
@tkanhe 
Thanks much 
Actually may be actually that day I would have attempted many times and hence would have ended up with the captcha error
Anyways now even the following works
https://github.com/tkanhe/Fyers-API-Access-Token-Generation-V2/blob/main/NEW%20Fyers%20Access%20Token.py
Thanks again for sharing the user agent agent stuff

Thanks,
Mahesh
