### ISSUE TITLE
login doesn't work

### ISSUE THREAD

**Issue by siddheshzele** [tkanhe/Fyers-API-Access-Token-Generation-V2#2]
Getting a access token!
Traceback (most recent call last):
  File "/Users/dev/Desktop/Python/fyerlogin.py", line 80, in <module>
    check()
  File "/Users/dev/Desktop/Python/fyerlogin.py", line 73, in check
    setup()
  File "/Users/dev/Desktop/Python/fyerlogin.py", line 37, in setup
    request_key = r1.json()["request_key"]
KeyError: 'request_key'

**Comment by tkanhe** [comment]
I just checked, working for me.
Would you please try running again?
Check the response "r1.json()" what it's saying?
Also, if you have just created the app and first time using it, then try the following:

session = accessToken.SessionModel(client_id=client_id, secret_key=secret_key, redirect_uri=redirect_uri, response_type='code', grant_type='authorization_code')

url = session.generate_authcode()

Go to the above URL and give permission to access the app; check if you get the access token. It's a one-time process. After that, you can use the script.

**Comment by tkanhe** [comment]
@siddheshzele I hope your issue has been solved. If yes, please close this issue.

**Comment by siddheshzele** [comment]
Ok
