### ISSUE TITLE
fyers-apiv2.0.4 vs fyers-apiv2.0.5

### ISSUE THREAD

**Issue by thepraveen19** [tkanhe/Fyers-API-Access-Token-Generation-V2#3]
Works with  fyers-apiv2.0.4
Does not work with fyers-apiv2.0.5

**Comment by tkanhe** [comment]
I just tried with both fyers-apiv2.0.5 & fyers-apiv2.0.4; it's working fine. Please try again. If you are still getting an error, please share it.

Thanks
