### ISSUE TITLE
Not sure where these links are coming from?

### ISSUE THREAD

**Issue by thepraveen19** [tkanhe/Fyers-API-Access-Token-Generation-V2#4]
https://api.fyers.in/vagator/v1/login
https://api.fyers.in/vagator/v1/verify_pin
https://api.fyers.in/api/v2/token

I am a newbie and trying to learn how it works. Although the code works like a gem, I fail to understand where these links are.
I checked by inspecting elements in the browser at all possible pages while logging in. Could not find it anywhere.
Could you please help understand this ?

**Comment by tkanhe** [comment]
If you reverse engineer the manual method of getting an access token, you will get those links.
`s = accessToken.SessionModel(client_id=client_id, secret_key=secret_key, redirect_uri=redirect_uri, response_type="code", grant_type="authorization_code")`

`url = s.generate_authcode()`
Follow the above URL in a browser.

**Comment by thepraveen19** [comment]
How did you reverse engineer the API?

**Comment by tkanhe** [comment]
By going to the following URL, just like you would get an access token manually.
> `url = s.generate_authcode()`
