### ISSUE TITLE
r3.status_code == 308

### ISSUE THREAD

**Issue by kkrunal77** [tkanhe/Fyers-API-Access-Token-Generation-V2#5]

**Comment by kkrunal77** [comment]
---> 43 assert r3.status_code == 308, f"Error in r3:\n {r3.json()}"
     45 # print(r3.json()['auth'])
     46 parsed = urlparse(r3.json()["Url"])
AssertionError: Error in r3:

This is because of created app is inactive?

**Comment by tkanhe** [comment]
Don't know. You can replicate it manually by going to the following url:
```
session = accessToken.SessionModel(client_id=client_id, secret_key=secret_key, redirect_uri=redirect_uri, response_type='code', grant_type='authorization_code')

url = session.generate_authcode()
```

**Comment by kkrunal77** [comment]
Thanks got the access
