### ISSUE TITLE
Assertion Error in vagator login

### ISSUE THREAD

**Issue by UmarAhmed129** [tkanhe/Fyers-API-Access-Token-Generation-V2#7]
My username and password are correct. I can login throug the browser, however while running code the vagator login endpoint throws the following assertion error

```
Cell In[4], line 272, in setup()
    270 data1 = f'{{"fy_id":"{username}","password":"{password}","app_id":"2","imei":"","recaptcha_token":""}}'
    271 r1 = s.post("https://api.fyers.in/vagator/v1/login", data=data1)
--> 272 assert r1.status_code == 200, f"Error in r1:\n {r1.json()}"
    274 request_key = r1.json()["request_key"]
    275 data2 = f'{{"request_key":"{request_key}","identity_type":"pin","identifier":"{pin}","recaptcha_token":""}}'

AssertionError: Error in r1:
 {'s': 'error', 'code': -1049, 'failed_attempts': 1, 'user_blocked': False, 'message': 'wrong username or password, 4 attempts left'}
```

Difference between browser login and python login is that browser does not ask for my password. First comes fyers id, then a sms is sent to my phone then 4 digit pin. Password is not asked.

I  have tried 3 times, each  time failed_attempts is 1 and 4 attempts are left ;-)

Update:
After 4 tries failed_attempts is now 2 and 3 attempts left

```
AssertionError: Error in r1:
 {'s': 'error', 'code': -1049, 'failed_attempts': 2, 'user_blocked': False, 'message': 'wrong username or password, 3 attempts left'}
```

**Comment by tkanhe** [comment]
Thank you for bringing up the issue. I think Fyers has recently implemented TOTP validation as part of their login procedure. Therefore, I have made the necessary changes to the code in order to integrate the latest Fyers API updates. Kindly check it now and let me know if it is functioning properly for you.

**Comment by UmarAhmed129** [comment]
@tkanhe @tk-cd 

I have undertaken the following steps

1. Went to my fyers account and copied the key while enabling the TOTP option (did not use any app on phone)
2. pasted the copied key in the file totp.py and ran the python code _python3 totp.py_ to generate a 6 digit totp key
3. entered the generated totp key along with my fyers pin and successfully activated External 2FA TOTP in fyers.
4. pasted the generated 6 digit totp key in the file fyers_access_token_totp.py in totp_key = "******"  # totp_key
5. ran the code to try login to fyers however I get the following error


```
Error: Non-base32 digit found

Cell In[5], line 438, in check()
    436 if "error" in response["s"] or "error" in response["message"] or "expired" in response["message"]:
    437     print("Getting a new fyers access token!")
--> 438     token = get_token()
    439     write_file(token)
    440     print(get_profile(token))

Cell In[5], line 400, in get_token()
    397 assert r1.status_code == 200, f"Error in r1:\n {r1.json()}"
    399 request_key = r1.json()["request_key"]
--> 400 data2 = f'{{"request_key":"{request_key}","otp":{totp(totp_key)}}}'
    401 r2 = s.post("https://api-t2.fyers.in/vagator/v2/verify_otp", data=data2)
    402 assert r2.status_code == 200, f"Error in r2:\n {r2.text}"

Cell In[5], line 378, in totp(key, time_step, digits, digest)
    377 def totp(key, time_step=30, digits=6, digest="sha1"):
--> 378     key = base64.b32decode(key.upper() + "=" * ((8 - len(key)) % 8))
    379     counter = struct.pack(">Q", int(time.time() / time_step))
    380     mac = hmac.new(key, counter, digest).digest()

File /usr/lib/python3.10/base64.py:253, in b32decode(s, casefold, map01)
    252 def b32decode(s, casefold=False, map01=None):
--> 253     return _b32decode(_b32alphabet, s, casefold, map01)

File /usr/lib/python3.10/base64.py:235, in _b32decode(alphabet, s, casefold, map01)
    233             acc = (acc << 5) + b32rev[c]
    234     except KeyError:
--> 235         raise binascii.Error('Non-base32 digit found') from None
    236     decoded += acc.to_bytes(5, 'big')
    237 # Process the last, partial quanta
```

I hope I have followed the steps correctly outlined in your README.md. 

Couple of thoughts

- Since External TOTP in fyers in optional, why should I enable it just to programmatically login to fyers
- Tried without TOTP using code in fyers_access_token_password.py and I got the exact same error while opening this issue. (Seems fishy that I can no more login just using my username, password and pin like I have been doing for the past several months using your excellent code )

**Comment by tkanhe** [comment]
Sorry for the confusion. To authenticate, kindly copy and paste the TOTP key which appears as "OMKR2YABCDVDFGECLWXKI6OVB7T4DTKU5". The python script will automatically generate the 6-digit TOTP for you.

In the event that external TOTP is not enabled, the user will have to rely on OTPs received via mobile or email for authentication. This may prove to be more challenging to automate.

Zerodha has been using the same authentication method for over a year now. It is worth noting that automating the token generation process is not recommended, as doing so could potentially compromise your credentials (username/pin/totp_key), especially if stored insecurely.

**Comment by UmarAhmed129** [comment]
@tkanhe 

Thanks for the clarification; authentication works correctly now after I pasted in the humongous TOTP key. 

I guess you are talking about Fyers and not Zerodha. 

Still I would like to go back to the normal username and password authentication without TOTP key that I had been using with your code. All of a sudden that does not work. 

Where in the workflow do I need to enter the OTP received via email or mobile for authentication using your code in the file fyers_access_token_password.py?

As for the automating the token generation process I am just storing my credentials in my app on my computer locally. I have not and do not intend to deploy my code anywhere or share with anyone. Is this still a security concern?

Thank you so much for your excellent code. Absolutely love it.

**Comment by tkanhe** [comment]
- With the recent addition of TOTP in the Fyers login process, the authentication process for Fyers and Zerodha is now the same.
- It is no longer possible to revert to the less secure method of username and password authentication since 2FA, such as TOTP authentication, is now recommended & mandatory.
- When logging in to the Fyers website, you will be required to use the 6-digit TOTP for authentication. You can generate this code using an authenticator app like Google or Microsoft Authenticator or by using the script provided [here](https://github.com/tkanhe/totp-generator), or both. Once you enable external 2FA, you will no longer receive OTPs via email or mobile.
- The fyers_access_token_password.py method is only available for those who have not yet changed their workflow. This method of authentication will be deprecated in the near future.
- If you store your credentials locally, it can pose a security concern if you lose your laptop and the storage is not encrypted.

Hope this helps.

**Comment by UmarAhmed129** [comment]
Absolutely, I am on a desktop though ;-)
